version: 2.1

orbs:
  pipecd: pipe-cd/pipecd@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
parameters:
  run-integration-tests:
    type: boolean
    default: false

  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  test:
    executor: pipecd/default
    steps:
      # test orb commands
      - pipecd/event-register:
          event-name: helm-release
          data: v0.23.0
          labels: env=knanao-dev

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - shellcheck/check:
          exclude: "SC1073, SC1009"
      - orb-tools/pack
      - approve:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - shellcheck/check
      - orb-tools/publish-dev:
          orb-name: pipe-cd/pipecd
          context: orb-publishing
          requires:
            - approve
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test
      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: pipe-cd/pipecd
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: 16:ba:d2:80:20:18:af:bf:d4:62:6b:79:1c:65:00:00
          requires:
            - test
          filters:
            branches:
              only:
                - master
